MaxSimultaneousGames: 10
TurnSeconds: 15
FinishedSeconds: 10
StartingHealth: 100
StartingHandSize: 3
RankedStolenPoints: 15
DefaultLanguage: "english"
AvailableLanguages:
- "english"
WorldName: "BlockBattlesWorld"
Locations:
  Reference:
    X: 0
    Y: 0
    Z: 0
  BoardSize:
    X: 8
    Y: 20
    Z: 8
  Player1SpawnPoint:
    X: 0
    Y: 0
    Z: 0
    Yaw: 0
    Pitch: 0
  Player2SpawnPoint:
    X: 0
    Y: 0
    Z: 0
    Yaw: 0
    Pitch: 0
  Exit:
    World: "world"
    X: 0
    Y: 0
    Z: 0
Items:
  JackOLantern:
    DamageDay: 2
    DamageNight: 5
  Chest:
    Damage: 5
  OakDoor:
    Damage: 4
    MaxInteractions: 3
    SecondsToInteract: 1
  OakFenceGate:
    Damage: 4
    MaxInteractions: 3
    SecondsToInteract: 1
  OakTrapdoor:
    Damage: 8
  Torch:
    Damage: 6
  RedstoneLamp:
    Damage: 5
  FlowerPot:
    Damage: 2
  PointedDripstone:
    Damage: 6
  WaxedExposedCutCopperStairs:
    Damage: 5
  DayLightDetector:
    Damage: 3
